### ISSUE TITLE
Adding Nintendo platform

### ISSUE THREAD

**Issue by kanokanor** [ugoogalizer/autoshift-scraper#1]
Hello,

Is it possible to add Nintendo to the platforms?

**Comment by ugoogalizer** [comment]
Hey, 

None of the mental mars website tracks them separately. Are you aware of any other sources that do? Or whether they're the same as any other platform?

**Comment by kanokanor** [comment]
Switch releases are very recent, so most of the multiplatform codes works with it. Currently I don't know about specific platform codes.

![image](https://github.com/ugoogalizer/autoshift-scraper/assets/36675539/fa07ea24-f38f-47ca-a8cb-ba25cf09b14d)

**Comment by ugoogalizer** [comment]
Well at a minimum then that means they work for the universal codes, and I don't think the scraper needs to change. It's the actual autoshift code (that's in a seperate repo here: https://github.com/ugoogalizer/autoshift ) that needs to have Nintendo added...

**Comment by ugoogalizer** [comment]
Hey, 

I've made some minor changes to the autoshift code to add it. 

I don't have nintendo activated on my shift account, so don't believe I can test it easily.  You can either run it directly as python from the repo, or you can use the docker image with tag `beta-nintendo` and tell me what happens (ugoogalizer/autoshift:beta-nintendo)

**Comment by kanokanor** [comment]
I'm sorry that I not opened this on the main repo but issues pages does not appear there.

As far I see it works perfectly with the set nintendo tag.
![image](https://github.com/ugoogalizer/autoshift-scraper/assets/36675539/fecf8703-fbc0-464c-936c-5a4749e362dc)
![image](https://github.com/ugoogalizer/autoshift-scraper/assets/36675539/c95e1f33-f335-46ed-adf9-ef31981cd417)

Many thanks!

**Comment by ugoogalizer** [comment]
Glad to hear it, I've pushed that update into `latest` then for anyone else who needs it. Will close this issue now
